# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: centos:7.9.2009

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:centos-7
        working_dir: /root

    build_flavour: c.7

  roles:
    - build
...
