# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: registry.access.redhat.com/ubi8/ubi:8.9

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:rhel-8
        working_dir: /root

    build_flavour: r.8

  roles:
    - build
...
