# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: amazonlinux:2023

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:aws-2023
        working_dir: /root

    build_flavour: w.2023

  roles:
    - build
...
