# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: oraclelinux:7.9

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:oel-7
        working_dir: /root

    build_flavour: o.7

  roles:
    - build
...
