# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: registry.access.redhat.com/ubi9/ubi:9.3

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:rhel-9
        working_dir: /root

    build_flavour: r.9

  roles:
    - build
...
