# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: centos:8.4.2105

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:centos-8
        working_dir: /root

    build_flavour: c.8

  roles:
    - build
...
