# vim: set ft=yaml.ansible:
---
- name: Build antest images
  hosts: localhost
  diff: true

  vars:
    ansible_bender:
      base_image: docker.io/dokken/centos-stream-9:main

      cache_tasks: false
      layering: false

      target_image:
        cmd: /sbin/init
        name: antest:centos-9
        working_dir: /root

    build_flavour: c.9

  roles:
    - build
...
