# vim: set ft=yaml.ansible:
---
- name: Template ansible-bender playbook
  hosts: localhost
  gather_subset: [ 'min' ]
  diff: true

  vars:
    _b: "{{ build_flavours[flavour] }}"

  tasks:
    - name: Assert that all needed vars is defined
      assert:
        that:
          - flavour is defined
          - _b.os_family is defined
          - _b.distribution is defined
          - _b.major_version is defined
          - _b.minor_version is defined

    - name: Render playbook template
      template:
        src: build.yml.j2
        dest: build.yml
        mode: "0644"

- name: Pre-build fucking damned OS image
  hosts: localhost
  gather_subset: [ 'min' ]
  diff: true

  vars:
    _b: "{{ build_flavours[flavour] }}"
    _build_ubuntu_image: "{{ _b.distribution }}:{{ _b.major_version }}.{{ _b.minor_version }}"

  tasks:
    - name: Damn OS condition
      when: _b.distribution == 'ubuntu'
      block:
        - name: Get existing images list
          register: __build_podman_images
          command:
            argv:
              - podman
              - images
              - --noheading
              - --format
              - !unsafe "table {{.Repository}}:{{.Tag}}"

        - name: Build if notexistent
          when: "'localhost/' ~ _build_ubuntu_image not in __build_podman_images.stdout_lines"
          block:
            - name: FROM
              command:
                argv:
                  - buildah
                  - from
                  - --name
                  - damned-working-container
                  - "{{ _build_ubuntu_image }}"

            - name: RUN
              command:
                argv:
                  - buildah
                  - run
                  - damned-working-container
                  - --
                  - /bin/bash
                  - -c
                  - "apt-get update && apt-get --yes --no-install-recommends install python-is-python3 && apt-get clean"

            - name: COMMIT
              command:
                argv:
                  - buildah
                  - commit
                  - damned-working-container
                  - "localhost/{{ _build_ubuntu_image }}"
          always:
            - name: RM
              command:
                argv:
                  - buildah
                  - rm
                  - damned-working-container
...
